name = "crypto-news-dingding"
main = "src/index.ts"
compatibility_date = "2024-10-16"
compatibility_flags = [ "nodejs_compat" ]

account_id = ""

[vars]
DINGDING_ACCESS_TOKEN = ""
DINGDING_SECRET_KEY = ""

[[kv_namespaces]]
binding = "CRYPTO_NEWS_DINGDING_KV"
id = ""

[triggers]
crons = ["*/1 * * * *"]